FROM node:20-alpine AS dev-build
WORKDIR /build
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run lint

FROM node:20-alpine as dev
WORKDIR /app
COPY --from=dev-build /build .
CMD ["npm", "run", "start:dev"]

FROM node:20-alpine AS prod-build
WORKDIR /build
COPY --from=dev-build /build .
RUN npm run build

FROM node:20-alpine AS prod
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev \
    && npm cache clean --force
COPY --from=prod-build /build/dist ./dist
COPY . .
CMD ["npm", "run", "start:prod"]
