FROM kalilinux/kali-rolling AS kali
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update \
    && apt install curl -y \
    && cp /etc/apt/sources.list /etc/apt/sources.list.bck \
    && curl -s 'http://http.kali.org/README.mirrorlist' | grep 'prio 100' | grep -P '\((cz|de|fr|eu|us),' | head -1 | sed 's|.*href="\([^"]*\)/README".*|deb \1 kali-last-snapshot main contrib non-free|g' > /etc/apt/sources.list \
    && cat /etc/apt/sources.list \
    && apt dist-upgrade -y \
    && apt update \
    && apt autoremove -y \
    && apt install python3-pip libpq-dev python3-dev libmagic1 libcap2-bin -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/*
RUN apt update \
    && apt install wordlists seclists dirb -y \
    && gzip -d /usr/share/wordlists/rockyou.txt.gz \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/*
RUN apt update \
    && apt install nmap smap -y \
    && apt install wget -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && pip install emailfinder ssh-audit
RUN wget https://nodejs.org/dist/v16.18.1/node-v16.18.1-linux-x64.tar.gz \
    && tar -xzf node-v16.18.1-linux-x64.tar.gz \
    && cp -r node-v16.18.1-linux-x64/* /usr/ \
    && rm -rf node-v16* \
    && npm install pm2 --location=global

FROM node:16.18.1-alpine AS dev-build
WORKDIR /build
COPY package.json ./
RUN npm i
COPY . .
RUN npm run lint

FROM kali AS dev
WORKDIR /app
COPY --from=dev-build /build .
CMD ["bash", "-c", "npm run start:dev"]

FROM node:16.18.1-alpine AS prod-build
WORKDIR /build
COPY --from=dev-build /build .
RUN npm run build

FROM kali AS prod
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev \
    && npm cache clean --force
COPY --from=prod-build /build/dist ./dist
COPY . .
CMD ["bash", "-c", "npm run start:prod"]
